apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-adservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eshop-adservice
  template:
    metadata:
      labels:
        app: eshop-adservice
    spec:
      containers:
        - name: eshop-adservice
          image: gcr.io/architect-certification-289902/31/eshop-adservice:4
          ports:
          - containerPort: 8095
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgresql-postgresql-ha-postgresql.default.svc.cluster.local:5432/eshop_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "eshop_user"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "password" 
---
apiVersion: v1
kind: Service
metadata:
  name: eshop-adservice
spec:
  type: ClusterIP
  selector:
    app: eshop-adservice
  ports:
  - name: api
    port: 8095
    targetPort: 8095
  